/*
 * Päivitysloki: mitä kussakin versiossa muuttui.
 *
 * Omistajan toive: "Tee erittäin tiivis päivitysloki joka tulee
 * näkyviin klikkaamalla versionumeroa kartalla."
 *
 * ERITTÄIN TIIVIS on tässä muotovaatimus, ei tyyliohje. Yksi rivi per
 * versio, korkeintaan noin 60 merkkiä, ilman versiohistorian tavallista
 * jargonia. Lokia luetaan puhelimen ruudulla kartan päältä, ja jos
 * riviä joutuu vierittämään, se on liian pitkä. Testi vahtii pituuden.
 *
 * Uusin ensin. Uusi rivi lisätään aina versionoston yhteydessä.
 * Vanhat rivit eivät muutu — loki on historia, ei kuvaus nykytilasta.
 */
export const MUUTOKSET = [
  { v: 259, teksti: 'Uusi vesistölinssi: pelkät joet ja järvet' },
  { v: 259, teksti: 'Jokien nimet takaisin vesistölinssin kanssa' },
  { v: 259, teksti: 'Tutki-otsikon tausta ei enää näy tummana palkkina' },
  { v: 258, teksti: 'Tutki: osaston otsikko pysyy näkyvissä vierittäessä' },
  { v: 257, teksti: 'Isot järvet takaisin kartalle, vain joet pois' },
  { v: 257, teksti: 'Radio kiinni alareunaan ja hieman kapeammaksi' },
  { v: 257, teksti: 'VU-neula ei jää kuolleeksi soivan aseman päälle' },
  { v: 257, teksti: 'Tutki-tekstin koko tuli oikeasti voimaan' },
  { v: 256, teksti: 'Tutki: leipäteksti luettavalla kirjasimella' },
  { v: 256, teksti: 'Osastojen otsikot lehden tapaan viivojen väliin' },
  { v: 256, teksti: 'Kappalejako, lihavoitu aloitus ja anfangi' },
  { v: 256, teksti: 'Sivulle sitaattinosto kuin aikakauslehdessä' },
  { v: 255, teksti: 'Joet ja järvet pois kartalta: tulossa oma linssi' },
  { v: 255, teksti: 'Taikalasien kuvake: silmälasit, ei suurennuslasi' },
  { v: 254, teksti: 'Joen nimi vain kerran ja aina samassa kohdassa' },
  { v: 254, teksti: 'Merisyvyys pois: ei sinistä, kevyempi vieritys' },
  { v: 254, teksti: 'Joet vaimeammiksi, ei enää viileää välkettä' },
  { v: 254, teksti: 'Topografialinssin vedet samaan musteeseen' },
  { v: 253, teksti: 'Kartan vieritys taas sujuvaa: rae 11x halvempi' },
  { v: 253, teksti: 'Maastonimet kaupunkien nimien kokoisia' },
  { v: 253, teksti: 'Maastonimet vasta kun kaupunkien nimet näkyvät' },
  { v: 253, teksti: 'Logon rivit tasavälein, ei enää kuoppaa keskellä' },
  { v: 252, teksti: 'Vesi on nyt mustetta ja paperia, ei sinistä' },
  { v: 252, teksti: 'Matkakirjan palkki vain sanojensa levyinen' },
  { v: 252, teksti: 'Logon rivit täsmälleen yhtä leveät' },
  { v: 251, teksti: 'VU-mittari pitää aseman herkkyyden koko ajan' },
  { v: 251, teksti: 'Merisyvyys hillitymmäksi: ei enää vuoda rannan yli' },
  { v: 251, teksti: 'Matkakirjan palkki vain otsikkonsa levyinen' },
  { v: 251, teksti: 'Äänet ja taikalasit hampurilaisen alle' },
  { v: 250, teksti: 'Maa erottuu merestä selvästi omalla värillään' },
  { v: 250, teksti: 'Hampurilainen takaisin: säännöt ja uusi peli sen alle' },
  { v: 249, teksti: 'Kutistettuun matkakirjaan jää otsikko ja tausta' },
  { v: 249, teksti: 'VU-mittari palaa asemalle myös kaupunkia vaihtaessa' },
  { v: 249, teksti: 'Merenpohja rajataan piirrettyyn rantaviivaan' },
  { v: 248, teksti: 'Pelin nimi: Matkakirja ja unohdettu aarre' },
  { v: 248, teksti: 'Yläpalkissa nimilogo: viiva ja alanimi' },
  { v: 247, teksti: 'VU-mittari sai lähetykselle oman asteikkonsa' },
  { v: 247, teksti: 'Neula näyttää ohjelman tason, ei nupin asentoa' },
  { v: 246, teksti: 'Meren sinisyys ei enää vuoda maiden päälle' },
  { v: 246, teksti: 'VU-mittari liikkuu myös CORSittomilla asemilla' },
  { v: 246, teksti: 'Kanavanvaihdon häivytys 0,9 sekuntiin' },
  { v: 245, teksti: 'Paperin pinta näkyy nyt myös lähikuvassa' },
  { v: 245, teksti: 'Kanavanvaihdon häivytys selvästi pidempi' },
  { v: 244, teksti: 'VU-mittari sai lähetyksen myös hitaalla alulla' },
  { v: 244, teksti: 'Panaman kuvakortti ei enää kahdennu' },
  { v: 243, teksti: 'Matkakirja kutistuu riviksi karttaa vierittäessä' },
  { v: 243, teksti: 'Linssin selite kutistuu ja avautuu napauttamalla' },
  { v: 242, teksti: 'Ikkunan avaus ei enää korosta ensimmäistä nappia' },
  { v: 241, teksti: 'Jokien nimet pysyvät paikallaan vierittäessä' },
  { v: 241, teksti: 'Nimen koko seuraa zoomia' },
  { v: 241, teksti: 'Maastoon enemmän syvyyttä lähikuvassa' },
  { v: 241, teksti: 'Tutki: ylä- ja alareunasta pääsee päähän' },
  { v: 241, teksti: 'Pelin nimi mahtuu vihdoin iPhonen ruudulle' },
  { v: 240, teksti: 'Tutki on nyt taitettu lehti: pyyhkäise sivuja' },
  { v: 240, teksti: 'Kuvat isommiksi ja tekstin lomaan' },
  { v: 240, teksti: 'Korjattu: kuvat katosivat iPadilla kokonaan' },
  { v: 240, teksti: 'Suurennus aina suorassa ja täydessä koossa' },
  { v: 240, teksti: 'Tutki täyttää puhelimen ruudun reunasta reunaan' },
  { v: 240, teksti: 'Joet kapeammiksi, maastonimet isommiksi' },
  { v: 240, teksti: 'Matkalaukusta lähteet ja tekijätiedot' },
  { v: 239, teksti: 'Kartta lämpimämmäksi, korkeus punaruskeaan' },
  { v: 239, teksti: 'Viritysääni kuuluu taas myös äänet pois päältä' },
  { v: 239, teksti: 'VU-mittari seuraa lähetystä 98 asemalla' },
  { v: 239, teksti: 'Radiokanava kaikkiin 110 maahan' },
  { v: 239, teksti: 'Hiiren rulla zoomaa karttaa työpöydällä' },
  { v: 239, teksti: 'Zoomaus hitaammaksi, ei enää tökkimistä' },
  { v: 239, teksti: 'Topografialinssin yläreuna sai värinsä' },
  { v: 239, teksti: 'Ylärivin napit isommiksi puhelimessa' },
  { v: 238, teksti: 'New York ja Rio vievät nyt maailmankartalle' },
  { v: 238, teksti: 'Saapumisessa ei enää välähdä koko maailma' },
  { v: 238, teksti: 'Zoomaus alkaa kauempaa ja laskeutuu pehmeästi' },
  { v: 238, teksti: 'Pelin nimi pienemmäksi puhelimen ylärivillä' },
  { v: 237, teksti: 'Hampurilainen pois: säännöt ja uusi peli riville' },
  { v: 237, teksti: 'Päivitys ja kehittäjätila versionumeron takaa' },
  { v: 237, teksti: 'Radiotilassa vain kartta ja soitin' },
  { v: 237, teksti: 'Kanavalista hehkuu epätasaisesti, lasi syvenee' },
  { v: 237, teksti: 'Viritys häipyy sisään ja ulos ristikkäin' },
  { v: 237, teksti: 'Viritysnauha nykii kuin oikea rulla' },
  { v: 237, teksti: 'VU-mittari seuraa myös lähetystä' },
  { v: 237, teksti: 'Pelin nimi kahdelle riville puhelimessa' },
  { v: 236, teksti: 'Radion kytkimet kuluneiksi, valoläiskät pois' },
  { v: 235, teksti: 'Maastonimet vaakaan ja isommalla' },
  { v: 235, teksti: 'Versionumero ei enää tummu laatikoksi' },
  { v: 234, teksti: 'Saapumisessa zoomaus, kohdemanner näkyviin' },
  { v: 234, teksti: 'Lento kestää repliikin lukemisen ajan' },
  { v: 234, teksti: 'Pieni nuoli ohittaa lennon halutessa' },
  { v: 234, teksti: 'Loitonnus ei enää näytä samaa paikkaa kahdesti' },
  { v: 234, teksti: 'Tangeriin tarkka markkinakuva Grand Socolta' },
  { v: 233, teksti: 'Beringinsalmi ehjäksi: Tšukotkan kärki takaisin' },
  { v: 233, teksti: 'Radiossa soiva kaupunki näkyy punaisena' },
  { v: 232, teksti: 'Kartta jatkuu ehjänä laudan reunan yli' },
  { v: 232, teksti: 'Kartta tarkentuu zoomatessa eikä sumene' },
  { v: 232, teksti: 'Uusi kuvake: kultainen aarre kahden pallon välissä' },
  { v: 231, teksti: 'Pelin nimi on nyt Unohdettu aarre' },
  { v: 231, teksti: 'Avausteksti tiiviimmäksi, luenta 34 s → 23 s' },
  { v: 230, teksti: 'Siperia ja Alaska yhtyvät ehjänä rantana' },
  { v: 230, teksti: 'Radio näkyy matkalaukussa' },
  { v: 230, teksti: 'Versionumero pois matkakirjan päältä' },
  { v: 229, teksti: 'Aarteet ovat nyt unohdettuja aarteita' },
  { v: 229, teksti: 'Tarinaan Aarnin luettelo, pelin ajojahti' },
  { v: 228, teksti: 'Radion äänisäädin pois, kytkimille tilaa' },
  { v: 228, teksti: 'Viisi aitoa lyhytaaltoäänitystä viritykseen' },
  { v: 227, teksti: 'Radion asteikossa naapurikaupungit, klikattavina' },
  { v: 227, teksti: 'Kromatut vipukytkimet ja hehkuva merkkivalo' },
  { v: 227, teksti: 'Viritysääni kun radio hakee kanavaa' },
  { v: 227, teksti: 'Kyrilliset ja kiinalaiset merkit näytölle' },
  { v: 227, teksti: 'Vanhat vedokset seitsemään kaupunkiin lisää' },
  { v: 226, teksti: 'Aarteella on oma nimi jokaisella laudalla' },
  { v: 226, teksti: 'Maailmankartan aarrekuulutus ei väitä Meripihkahuonetta' },
  { v: 225, teksti: 'Avauslento esittelee pelin idean ääneen' },
  { v: 225, teksti: 'Lennot muistuttavat unohdetusta aarteesta' },
  { v: 224, teksti: 'Maailmanradio: kaupungit soivat kartalta' },
  { v: 224, teksti: 'Vanhan ajan radiosoitin ruudun alalaitaan' },
  { v: 224, teksti: 'Kehittäjätilaan kaikki toimivat aarteet' },
  { v: 223, teksti: 'Järvet, joet ja vuoristot nimetty kaunolla' },
  { v: 223, teksti: 'Vesi saa syvyyden ja värin lähelle zoomatessa' },
  { v: 223, teksti: 'Joet levenevät uomiksi kun karttaa katsoo läheltä' },
  { v: 223, teksti: 'Nimen perässä i avaa paikan tarinan' },
  { v: 222, teksti: 'Kuvat kaikkiin 248 kaupunkiin' },
  { v: 222, teksti: 'Uusi alue piirtyy viisi kertaa nopeammin' },
  { v: 222, teksti: 'Korjattu: joet eivät näkyneet kartalla lainkaan' },
  { v: 222, teksti: 'Järvet ja joet meren sävyyn, sininen pois' },
  { v: 221, teksti: 'Matkakirja valmis: 248 paikkaa, 248 luentaa' },
  { v: 221, teksti: 'Amerikat ja Oseania kirjoitettu ja luettu' },
  { v: 221, teksti: 'Kertoja eläytyy: huikeat paikat kuuluvat äänessä' },
  { v: 220, teksti: 'Tutki-aiheet valmiit monistettaviksi muualle' },
  { v: 220, teksti: 'Lontoon metro, Proms ja piirakka aiheisiin' },
  { v: 220, teksti: 'Aiheisiin Lue lisää -napit ja musiikkilinkit' },
  { v: 219, teksti: 'Loput 13 luentaa: koko Aasia on nyt luettu' },
  { v: 218, teksti: 'Korjattu: Tutki-ikkuna ei auennut monessa kaupungissa' },
  { v: 217, teksti: 'Vuoret, joet ja järvet kartalle' },
  { v: 217, teksti: 'Korjattu: kuvat jäivät välillä lataamatta' },
  { v: 217, teksti: 'Himalajan lumi ei enää näytä reiältä' },
  { v: 216, teksti: 'Aasian ja Lähi-idän merkinnät uusiksi' },
  { v: 216, teksti: 'Kertojan luenta 50 uuteen kaupunkiin' },
  { v: 215, teksti: 'Luennat eivät enää lopu napsahdukseen' },
  { v: 214, teksti: 'Uudet kaupungit: Asunción, Montevideo, Houston, Havanna' },
  { v: 213, teksti: 'Nipistys zoomaa karttaa — nyt oikeasti' },
  { v: 213, teksti: 'Zoomipainikkeet pois kosketuslaitteilta' },
  { v: 212, teksti: 'Koko Eurooppa kirjoitettu uusiksi ja luettu' },
  { v: 212, teksti: 'Kertojan luenta kaikkiin 41 Euroopan kaupunkiin' },
  { v: 211, teksti: 'Nipistys zoomaa karttaa kahdella sormella' },
  { v: 211, teksti: 'Korjattu: kartta katkesi kesken kierroksen' },
  { v: 210, teksti: 'Pohjolan merkinnät uusiksi yhden idean malliin' },
  { v: 209, teksti: 'Maailmankartta korvasi vanhan maailman laudan' },
  { v: 209, teksti: 'Maat, rajat ja matkakirja maailmankartalle' },
  { v: 209, teksti: 'Kesken jäänyt peli siirtyy uudelle kartalle' },
  { v: 209, teksti: 'Työhuone laski puutteita liian ankarasti' },
  { v: 208, teksti: 'Helsingin merkintä uusiksi: kaupunki pala palalta' },
  { v: 207, teksti: 'Baltian merkinnät lyhyemmiksi ja selkeämmiksi' },
  { v: 206, teksti: 'Koko maailma yhtenä karttana: 248 kaupunkia' },
  { v: 206, teksti: 'Kartta kiertää ympäri eikä pääty reunaan' },
  { v: 206, teksti: 'Valtameriylitykset yhdistävät mantereet' },
  { v: 206, teksti: 'Kartta latautuu kolmekymmentä kertaa nopeammin' },
  { v: 205, teksti: 'Korjattu: nostojen kuvat puuttuivat iPhonelta' },
  { v: 204, teksti: 'Aiherivi pysyy näkyvissä arkin yläreunassa' },
  { v: 203, teksti: 'Kuvat omissa mittasuhteissaan, ei panoraamana' },
  { v: 203, teksti: 'Aiheen vaihto ei enää hyppää näkymässä' },
  { v: 203, teksti: 'Väljemmät marginaalit Tutki-arkilla' },
  { v: 203, teksti: 'Afrikan aarre: Suuren Zimbabwen kivilintu' },
  { v: 202, teksti: 'Arkin reuna piirtyy kuin rantaviiva kartalla' },
  { v: 202, teksti: 'Tutki-kortti täyttää ruudun muistiinpanoarkkina' },
  { v: 202, teksti: 'Aiheliuskat kuvakkeina yhdelle riville' },
  { v: 201, teksti: 'Tutki-ikkunaan kirjanmerkkiliuskat aiheittain' },
  { v: 201, teksti: 'Lontooseen 53 kulttuurinostoa yhdeksään aiheeseen' },
  { v: 200, teksti: 'Työhuone ei enää syö pelin offline-muistia' },
  { v: 200, teksti: 'Turha päivityskehotus pois työhuoneesta' },
  { v: 199, teksti: 'Kaupungin oma ääni soi vihdoin isolla laudalla' },
  { v: 198, teksti: 'Radionapissa aseman nimi ja live-merkki' },
  { v: 198, teksti: 'Vain aidosti vanhat kuvat ovat mustavalkoisia' },
  { v: 198, teksti: 'Kuvat aukeavat isompina työpöytäselaimella' },
  { v: 198, teksti: 'Sisältötarkastus: 15 virhettä pois teksteistä' },
  { v: 198, teksti: 'Pariisin ja Lontoon tekstit vastaavat kertojaa' },
  { v: 197, teksti: 'Laajennussuunnat työhuoneen suunnitelmaan' },
  { v: 196, teksti: 'Työhuoneen karttakehys ei jää soimaan taustalle' },
  { v: 196, teksti: 'Työhuone näyttää peilin ja repojen koot' },
  { v: 196, teksti: 'Äänistudio työhuoneen sisään, oma sivu pois' },
  { v: 195, teksti: 'Äänistudio samaan tyyliin työhuoneen kanssa' },
  { v: 194, teksti: 'Työhuone uusiksi: selkeämpi ja oma sovellus' },
  { v: 193, teksti: 'Tunnusluvut 21 Aasian maalle' },
  { v: 192, teksti: 'Kuvakortit 40 Aasian kaupunkiin' },
  { v: 191, teksti: 'Päivitysloki versionumeron takana' },
  { v: 190, teksti: 'Lipputunnistus uutena kysymysmuotona' },
  { v: 190, teksti: 'Europeana mukaan kuvahakuun' },
  { v: 189, teksti: 'Maiden rajat Aasiaan: 84 maata minikartalla' },
  { v: 188, teksti: 'Omat artikkelit kaikkiin 143 kaupunkiin' },
  { v: 187, teksti: 'Suora radio kaikkiin 87 maahan' },
  { v: 186, teksti: '193 uutta kuvaa päiväkirjan näkymistä' },
  { v: 186, teksti: 'Korjattu: Lue lisää kaatui 69 paikassa' },
  { v: 185, teksti: 'Saapumistekstit kaikkiin 143 kaupunkiin' },
  { v: 185, teksti: 'Kuuntele kieltä soittaa suoraa radiota' },
  { v: 185, teksti: 'Korjattu: Darfurin kuva ei ollut vanha' },
  { v: 184, teksti: 'Kuvakortti keskelle ruutua' },
  { v: 183, teksti: 'Kuvapino kestää useamman kuin kaksi kuvaa' },
  { v: 182, teksti: 'Kuvakortti isommaksi isolla ruudulla' },
  { v: 181, teksti: 'Työhuoneeseen oma välilehti laseille' },
  { v: 180, teksti: 'Noppa takaisin yhdistetylle kartalle' },
  { v: 178, teksti: 'Wiki, ääni ja maa 66 uudelle kaupungille' },
  { v: 176, teksti: 'Kertojan ääni ei enää naksahda lopussa' },
  { v: 174, teksti: 'Korsika kartalle' },
  { v: 172, teksti: 'Tutki-ikkuna mahtuu puhelimen ruudulle' },
  { v: 169, teksti: 'Tiet näkyvät taas iPadilla' },
  { v: 167, teksti: 'Vinjetointi pois kaikilta laitteilta' },
  { v: 166, teksti: 'Kartta ei välky uutta osaa ladatessa' },
  { v: 165, teksti: 'Kartta bittikarttana: sujuva vieritys' },
  { v: 160, teksti: 'Lähizoomaus kaupunkiin saavuttaessa' },
  { v: 159, teksti: 'Meri näkyy taas iPadilla' },
  { v: 155, teksti: 'Yhdistetty vanha maailma yhdeksi kartaksi' },
];
